apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.${dns_zone}
  statusbadge.enabled: "true"
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/${tenant_id}/v2.0
    clientID: ${client_id}
    clientSecret: ${client_secret}
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
