apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-github-${org_name}
  namespace: ${namespace}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: ${org_url}
  username: git
  password: ${pat}
